model_list:
  - model_name: minimax-m2.5
    litellm_params:
      model: openai/minimax-m2.5
      api_base: os.environ/LLAMA_API_BASE
      api_key: none

  - model_name: claude-sonnet-4-6
    litellm_params:
      model: openai/minimax-m2.5
      api_base: os.environ/LLAMA_API_BASE
      api_key: none
  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: openai/minimax-m2.5
      api_base: os.environ/LLAMA_API_BASE
      api_key: none

litellm_settings:
  drop_params: true
  num_retries: 2
  request_timeout: 300
