use_default_settings: true

search:
  formats:
    - html
    - json

server:
  secret_key: "umcode-local-dev"
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false

general:
  enable_metrics: false
